#!/bin/bash

function check_daemon {

  PID=$(pidof kueued)

  if [ -z "$PID" ] ; then 

      /etc/init.d/kueued stop
      /etc/init.d/kueued start
      echo "I had to restart kueued at $(date)" | mail -s "kueued @ $HOSTNAME" kueue@suse.de
  fi
}

function check_dbupdate {

  /etc/init.d/kueued-dbupdate status

  if [ "$?" != "0" ] ; then

      /etc/init.d/kueued-dbupdate start
      echo "I had to restart kueued-dbupdate at $(date)" | mail -s "kueued @ $HOSTNAME" kueue@suse.de
  fi
}


check_daemon
check_dbupdate


