#!/bin/bash
#
# copy to /usr/bin and run as cronjob
# 59 23 * * sun /usr/bin/rotate_kueued_logs

DATE=$(date +%Y%m%d)

/etc/init.d/kueued stop

cd /var/log/kueued

for i in *.log; do 

    mv $i $i.$DATE
    touch $i
    chown kueued $i

done

/etc/init.d/kueued start

for i in *.$DATE; do

    bzip2 $i

done
